name: github pages

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      
      - name: Where is yarn
        run: |
          echo $(yarn global bin)
          env
        working-directory: ./site
      
      - name: Where is yarn in bash
        run: |
          bash echo $(yarn global bin)
          bash env
        working-directory: ./site

      - name: install base packages
        run: yarn

      - name: build base packages
        run: yarn build

      - name: install site packages
        run: yarn
        working-directory: ./site

      - name: build docz site
        run: bash --noprofile --norc -eo pipefail yarn run build
        working-directory: ./site
        env:
          DOCZ_BASE: /helsinki-design-system/

      - name: build storybook site
        run: bash --noprofile --norc -eo pipefail yarn run build
        working-directory: ./packages/react

      - name: move storybook under docz
        run: mv ./packages/react/storybook-static ./site/public/storybook

      - name: Deploy
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./site/public
          SCRIPT_MODE: true
        run: |
          wget https://raw.githubusercontent.com/peaceiris/actions-gh-pages/v2.5.0/entrypoint.sh
          bash ./entrypoint.sh
          # with:
          # keepFiles: true
